### ISSUE TITLE
Heather Lim talk on Hanami and Ruby

### ISSUE THREAD

**Issue by heatherlim** [NYCrb/devpunks#14]
Am looking for the video link for my talk last year.

**Comment by snuggs** [comment]
Will look at this this evening. Attempted to edit but comp borked when render/upload happened. Will try again this evening. Also would you like to pair on moving some things around on the videos page of this site?

[This issue also fixes https://github.com/NYCrb/devpunks/issues/3]

**Comment by heatherlim** [comment]
What needs to be done?

**Comment by snuggs** [comment]
@heatherlim Done and DONE! You're the best with this and thanks for your patience. I hope I made you proud! https://www.youtube.com/watch?v=uoyFQteYeKc

Will be adding to website on a branch I will submit today. Will need your blessing before merging (will ping you). then it's up on the site and we're done. We can close this issue then.

P.S. You'll officially be known as the first talk as we are putting out videos the rest of the year. 😎

**Comment by snuggs** [comment]
@heatherlim have moved video to a new youtube channel. Will keep the other up for a bit before taking down. This URL will be the source of truth. Well done! We did it! (finally). Moving forward we're using this repository to collaborate on some things within the community. Thanks for contributing! Be on the lookout for a Week in Review summary email on Sunday with your video attached.

https://www.youtube.com/watch?v=88snSsNkDlU

Currently working on an upgrade on the main website to a video element but that doesn't stop you from sharing your great work. Did you see Hanami already tweeted us!

https://github.com/NYCrb/devpunks/pull/18
https://twitter.com/hanamirb/status/839736842111053824
