### ISSUE TITLE
Conf video in video element.

### ISSUE THREAD

**Issue by mrbernnz** [NYCrb/devpunks#15]
I was thinking probably the video should be set properly inside the video element better.

**Comment by snuggs** [comment]
I concur. Can you alley oop 🏀  an example of using youtube link in `<video>` element @mrbernnz ?

**Comment by mrbernnz** [comment]
After an hour of research. I think I found a solution. Youtube makes it crazy difficult to get the source video url. I'll make a little PR for it.

**Comment by snuggs** [comment]
Can the process be automated from their api @mrbernnz ?

**Comment by snuggs** [comment]
🕐  HELLOOOO @mrbernnz

**Comment by mrbernnz** [comment]
@snuggs Can you elaborate on what you mean by automated process?

**Comment by snuggs** [comment]
So we upload videos to youtube and it reads from API. Oh just answered my own question.

**Comment by mrbernnz** [comment]
@snuggs I haven't found a simple implementation through the API using a `video` tag. I have found work arounds that require an extra library. Until I can find a straight forward solution that wouldn't require extra code to have it work. `<iframe>` is going to be the de facto.

**Comment by brandondees** [comment]
did anybody check to ensure that it's not a violation of youtube TOS to even unwrap their embeds?

**Comment by mrbernnz** [comment]
@brandondees you maybe onto something.
![screenshot 2017-07-31 17 31 26](https://user-images.githubusercontent.com/9615028/28799454-a24fbc90-7616-11e7-8131-483cdea0ffeb.png)

But as far as I know, this language is not repeated in youtube API TOS.

**Comment by brandondees** [comment]
yeah, so if you authenticate to the api, you may be able to fetch video data that way and use it in a video tag, but according to A, if youtube didn't explicitly make the distribution means available to you, then it's prohibited.

**Comment by mrbernnz** [comment]
![meh](https://media.giphy.com/media/xT77Y8eeEhBA8NQwLK/giphy.gif)
