### ISSUE TITLE
GraphQL Talk Proposal for NYC.rb 3/14

### ISSUE THREAD

**Issue by bswinnerton** [NYCrb/devpunks#20]
👋 @snuggs,

Here's the talk proposal for next week's NYC.rb meetup. If there's anything I'm missing, just let me know and I'd be happy to fill in the gaps.

### Abstract

GraphQL is an exciting new query language that is changing the way we think about APIs and their design. In this talk, Brooks will introduce the query language, how it works in the world of Ruby and Rails, and how you can use it to power your next API. Finally, Brooks will discuss how GitHub is using GraphQL in production and what it took to get there.

### Bio

Brooks is a Platform Engineer at GitHub where he works on their REST API, GraphQL API, and webhooks.

**Comment by snuggs** [comment]
BOOM!!! THis is PERFECT @bswinnerton.

**Comment by snuggs** [comment]
@bswinnerton https://www.meetup.com/NYC-rb/events/231306351/
