### ISSUE TITLE
devPunks Facebook page for Job Opportunities

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#21]
@KageJordan can you secure the Facebook page? Is this even a good idea? There seems to be a new feature for posting job opportunities. We can use this as a stream as well.

We can use this as another way to funnel into opportunities. Would love to know what @joyceschiffer thinks of this as a strategy.

Currently I only have access to sneakyhead and i think that project is out of the scope of what we are doing here. /cc @melaniegershman @mrbernnz 

![capture d ecran 2017-03-08 a 12 08 05](https://cloud.githubusercontent.com/assets/38223/23714623/edebd1de-03f7-11e7-8550-4de59984cb66.png)
![capture d ecran 2017-03-08 a 12 07 55](https://cloud.githubusercontent.com/assets/38223/23714624/edecb19e-03f7-11e7-90e8-99e858d935d3.png)

**Comment by joyceschiffer** [comment]
I like the idea of posting my jobs to NYCrb Facebook page.  Might be worth a try.

 

 


 <http://www.ondawagroup.com/> 

Joyce Schiffer

203-241-2655

 <mailto:Joyce@OndawaGroup.com> Joyce@OndawaGroup.com
 <http://www.ondawagroup.com/> www.ondawagroup.com

 <http://www.facebook.com/ondawagroup>   <http://www.twitter.com/joyceschiffer>   <http://www.linkedin.com/in/joyceschiffer>

**Comment by snuggs** [comment]
We can tweet as well. All can be automated of course @joyceschiffer. Let's start simple with a first one. See who bites. Also will use as text at the meetup next week and for the announcement I need to send today. Feel free to layout some text here. @KageJordan knows how to play it out. 💪

**Comment by joyceschiffer** [comment]
HI Snuggs,  Is this what you want?

 

Looking for serious RoR Developers that want to join a growing disruptor that recently went public.

We are using RoR, ReactJs, Elixir and more.  Will train/mentor those looking to grow their skills.

 <https://www.linkedin.com/mjobs/jobPosting/editForm/266029837?trk=cap_mng_jobs> https://www.linkedin.com/mjobs/jobPosting/editForm/266029837?trk=cap_mng_jobs

 

 

 

 


 <http://www.ondawagroup.com/> 

Joyce Schiffer

203-241-2655

 <mailto:Joyce@OndawaGroup.com> Joyce@OndawaGroup.com
 <http://www.ondawagroup.com/> www.ondawagroup.com

 <http://www.facebook.com/ondawagroup>   <http://www.twitter.com/joyceschiffer>   <http://www.linkedin.com/in/joyceschiffer>

**Comment by snuggs** [comment]
Absolutely @joyceschiffer. Now coming up for air with Open Source stuff. Let's link soon so we can show what we've done. /cc @KageJordan
