### ISSUE TITLE
The Commit That Broke Github

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#25]
# #FreeBumbleBee [#a047be](https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac)
Would like to at least give a comedy skit by showing this commit. 

## Test Failure
![capture d ecran 2017-03-09 a 19 16 40](https://cloud.githubusercontent.com/assets/38223/23776580/1decb942-04fd-11e7-8724-35f3f91d344d.png)

**Comment by pachonk** [comment]
https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6f1dafc8beb84f2ac is the broken commit. I sent in a support request.

**Comment by pachonk** [comment]
The basis is probably doing something like `CommitComment.where(commit_sha: 'a047be85247755cdbe0acce6f1dafc8beb84f2ac')` and it returns an array larger than the max memory limit.

**Comment by pachonk** [comment]
Update: They fixed it after I emailed them

**Comment by pachonk** [comment]
Nevermind, it was working this AM. Maybe on mobile.

**Comment by pachonk** [comment]
![image](https://cloud.githubusercontent.com/assets/6721355/23776515/7699479e-04f4-11e7-9794-0ed80a705f1d.png)

**Comment by pachonk** [comment]
It's fixed

**Comment by pachonk** [comment]
Congratulations @snuggs, we contributed to Github!

**Comment by snuggs** [comment]
Wait what really @pachonk ???

**Comment by snuggs** [comment]
SWEET!

**Comment by pachonk** [comment]
It's awesome to think that the rubyonrails-link​ community contributed to GitHub with a legitimate and consistent 500 error.
