### ISSUE TITLE
How to use vim to it's fullest

### ISSUE THREAD

**Issue by grepsedawk** [NYCrb/devpunks#26]
I want to have a discussion to make ruby autocomplete, lint, rubocop.... all in vim. I've been using vim for awhile, but I've never really configured it to it's fullest.

**Comment by pachonk** [comment]
@snuggs

**Comment by brandondees** [comment]
FYI Upcase has a bunch of good materials covering vim basics and working up to all the power tool configuration stuff that the Thoughtbot folks use. I'm currently working through some of that material a little at a time. I had used Janus as a base config in the past but I'm going from scratch and picking up things one at a time this time, and finding I'm getting more out of it this way.

**Comment by pachonk** [comment]
Ah really? Thanks I'll look after I get through the TDD course.
I didn't even know you were on devPunks :+1:
