### ISSUE TITLE
[2017-06-22] A Better Technical Interview

### ISSUE THREAD

**Issue by samjonester** [NYCrb/devpunks#28]
A response to (rightfully) grumpy tweets about how technical interviews are ineffective. Candidates shouldn't be afraid that a technical interview won't reflect their true abilities. They should feel that an interview valuable even if the decision is "Not Yet".

**Let's make a valuable interview** by setting better expectations and creating better evaluation techniques.

**Let's make an honest interview** by asking instead of assuming, and treating candidates like they'll be treated on the team.

**Let's make a collective interview** by encouraging dialog and testing a candidate's to teach, learn, and work with teammates.

**Let's make a nice interview** by ensuring the process is valuable to the candidate even if they're not yet ready to join the team.

_______________________________________________________________________________

This talk is 20-25 minutes, and I've given it at a few other meetups.

**Comment by snuggs** [comment]
Sweet! June 13th it is!

**Comment by snuggs** [comment]
@samjonester https://www.meetup.com/NYC-rb/events/234790823/

**Comment by samjonester** [comment]
If you're able to chat this week, I've got availability Thursday the 29th between 2:30-5p EDT, and Friday the 30th between 1:30-4p EDT.
