### ISSUE TITLE
Free RubyMine license give-away

### ISSUE THREAD

**Issue by grepsedawk** [NYCrb/devpunks#32]
@snuggs Do you give away RubyMine? Jetbrains does 1 a month for meetups.

**Comment by snuggs** [comment]
WOW I did not know that @pachonk !!! #SCORE 🏀  What's the next step?

**Comment by pachonk** [comment]
I'll link when I get home.

**Comment by pachonk** [comment]
Not seeing it here: https://www.jetbrains.com/ruby/buy/#edition=discounts

I know it exists though, might have to contact them.

**Comment by pachonk** [comment]
Also, #freejewelry :gem: :ring:

**Comment by dmitrinesterenko** [comment]
@pachonk any luck with #freejetbrainz ?

**Comment by pachonk** [comment]
I didn't look, I just meant your meetup might need to contact them.
