### ISSUE TITLE
NYU Libraries Sponsorship

### ISSUE THREAD

**Issue by grepsedawk** [NYCrb/devpunks#33]
![](https://s-media-cache-ak0.pinimg.com/564x/dd/bb/ed/ddbbed13fd7874e79a75e931f34d7253.jpg)
### Carol Kassel

http://dlib.nyu.edu/dlts/staff/#kassel

**Comment by pachonk** [comment]
@snuggs I know Carol. If you would like me to perform introductions, let me know!

**Comment by snuggs** [comment]
AWESOME!!!!!! @pachonk

**Comment by pachonk** [comment]
@snuggs are you already in communication, or would you like me to open that line of communication?
What are you interested in asking her to sponsor?

**Comment by snuggs** [comment]
yes make it happen sir! Let them know i'm one of their adjuncts as well. Should make it more seamless.

**Comment by pachonk** [comment]
It would be easier to know what you want from them. Venue? 💰?

**Comment by snuggs** [comment]
BOTH! :-) Even offering to help them again as well wherever i can. @pachonk

**Comment by pachonk** [comment]
Sent!
Hi Carol and Rashaun,
As per Rashaun's request I would like to create a path of communication between both of you, as I believe you two can find arrangements for a very mutually beneficial relationship. Rashaun I'd a leader of NYC.rb as well as the founder of the JavaScript microframework "snuggsi" and they are currently looking for a venue to meet, as well as other various sponsorship opportunities.
Rashaun discussed with me briefly that he is willing to exchange assistance to yourself and your team for some form of sponsorship.
With his major pull in the NYC community, I believe this could potentially be a very mutually beneficial relationship.

Cheers,
Alex Piechowski
