### ISSUE TITLE
[2017-08-08] Destroy All Hashes: Rid yourself of primitive obsession to improve at OOP

### ISSUE THREAD

**Issue by ericfirth** [NYCrb/devpunks#34]
## Abstract
One of the hardest parts of getting better at Ruby for me was finding objects and not just making procedural code. What helped me was seeing my data as objects and using them as such rather than keeping them as hashes.

In this talk, I go over the problem where I learned that there where objects hidden in my data structures. I go over all the warning signs that I went past for quite a long time before I made the adjustment. I also go over what you get from the adjustment.

## Bio
Eric Firth is a software developer at Persado. He is a relatively recent (Jun '15) grad of the App Academy bootcamp. He was a designer before learning to code and is very picky about how code looks and feels.

**Comment by snuggs** [comment]
NICEEEE @ericfirth How's the 7/11 or the following month (second Tuesday) sound? You'd be presenting with @karlfloersch  /cc @brandondees @mrbernnz

**Comment by pachonk** [comment]
I want to see this, will it be recorded?

**Comment by snuggs** [comment]
We shall see @pachonk. And hopefully you will too :-)

**Comment by mrbernnz** [comment]
@snuggs Sound interesting to me. 👍

**Comment by pachonk** [comment]
Please please please make sure to say that hashes aren't totally unnecessary (unless that's what you believe) so the greener devs don't forever avoid hashes

**Comment by ericfirth** [comment]
I won't. Destroy All Hashes is more a catchy name for the talk. The talk is more about going from relying less on procedural code and finding the objects hidden in hashes.

**Comment by ericfirth** [comment]
@snuggs i realized i never answered your 7/11 or 8/8 question. tuesday feels soon to me, can i do this in august? i can come tuesday and talk if you'd like

**Comment by snuggs** [comment]
No worries! You know we are super accommodating. Especially when I know the effort it takes to give a talk. Also have empathy for "timing". Let's punt until August and let's link between now and then and can be a sounding board for your talk over a hangout or something. How's that sound @ericfirth ?

See you soon! >> https://www.meetup.com/NYC-rb/events/235117566/

**Comment by snuggs** [comment]
@ericfirth how you looking for August? If too soon 100% you should do September. Got people asking me about this. lol

**Comment by ericfirth** [comment]
@snuggs i'll be ready

**Comment by snuggs** [comment]
#BOOM @ericfirth !!! 💥
