### ISSUE TITLE
[2017-7-11] Ruby and Elm: A Love Story in the Making

### ISSUE THREAD

**Issue by noahzgordon** [NYCrb/devpunks#35]
## Abstract

Have you heard about this new front-end language called Elm? Did you know that it's super easy to integrate with your Rails applications? Did you know that it's freaking awesome?

In this talk, I will provide answers to the following questions:
+ what the heck is Elm?
+ why should I like Elm?
+ how can I create a new Rails application with an Elm front end in fewer than five minutes?

This talk is highly recommend for Rubyists who (a) love simple and elegant languages, and/or (b) hate Javascript. 

## Biography

Hi, it's me, Noah! I'm primarily a Ruby on Rails developer, but I love Elm dearly and want to see it succeed. I work at Gust, building products and features that help early-stage founders get off the ground and seek funding. I also organize and co-host the [Elm NYC](https://www.meetup.com/Elm-NYC/) meetup group, which meets on the first Thursday of every month. 

I also like video games, weird art and cats. Here's a picture of my cat being a little weirdo.

![Finn the Cat](https://user-images.githubusercontent.com/7379855/27911575-75d34b44-6227-11e7-9649-23f3d14fe37d.jpg)

**Comment by snuggs** [comment]
@noahzgordon https://www.meetup.com/NYC-rb/events/235117566
