### ISSUE TITLE
[2017-08-08] Rails API, React & Authentication: Secure, and Easy Token-Based Authentication

### ISSUE THREAD

**Issue by schmartmann** [NYCrb/devpunks#36]
## Abstract

I'm a huge fan of spinning up a front-end server running React, and a separate, back-end server using a Rails API, but found it frustrating to find a reliable way to handle authentication without hand-rolling. 

Enter: devise_token_auth and j-Toker

In this talk, I'll discuss the following: 
- What is token-based authentication? 
- How can we integrate devise_token_auth into a Rails app
- What is the most effective way for a front-end, React app to interact with this auth framework?

## Bio
Stefan Hartmann is a freelance developer, and a grad of the WDI program at General Assembly. He was a writer before learning code, and writes gratuitously long pseudocode.

**Comment by snuggs** [comment]
@schmartmann this is AWESOME! Look forward to hearing it.

**Comment by justin808** [comment]
* https://github.com/shakacode/react_on_rails
* https://www.youtube.com/watch?v=SGkTvKRPYrk

Aloha,

Justin

**Comment by snuggs** [comment]
@schmartmann ready to go? Will announce tonight.

**Comment by schmartmann** [comment]
@snuggs all ready!
