### ISSUE TITLE
[2017-10-10] Building a P2P Network in Ruby

### ISSUE THREAD

**Issue by davidkurutz** [NYCrb/devpunks#37]
## Abstract

Intrigued by modern and past peer to peer systems, I set out to build my own from scratch.

In this talk, I’ll discuss  my experience working in the P2P problem space, touching upon the following topics:

- Implementation of a distributed hash table.
- Reading whitepapers and translating them to code.
- What is Kademlia and how does it work?
- Simulating multi-node network communications in a local environment.

## Bio
David Kurutz is a software developer, a systems administrator, a musician, a dogfather, and pro-wrestling fan.

**Comment by brandondees** [comment]
I really want to see the video on this one. @snuggs what's the status on recordings?

**Comment by snuggs** [comment]
@brandondees we just published the NYC.rb/Goruco React on Rails one. https://www.youtube.com/watch?v=SGkTvKRPYrk
Working on next one as soon as I meet with editor next meetup.

https://www.youtube.com/watch?v=SGkTvKRPYrk

**Comment by snuggs** [comment]
@davidkurutz this is great man! when are you able to give this talk? We just announced august and sept is open for a short one. But truth be told i'd rather hear this one out in a long full length 30(ish) min talk. You think there's enough content for this? Can always fill space with a good Q&A. The more QA the better I always say.Your thoughts my man!

**Comment by davidkurutz** [comment]
@snuggs Thank you!!  I agree fully. I'll certainly have enough content to fill out a 30-ish minute slot. I'll be ready earlier, but waiting until October is fine by me.  I'll have presentation assets generated over the next week so you can have some project links, etc.  Thanks!

**Comment by snuggs** [comment]
yeah and want to do a hangout with you before hand to possibly to aa rough draft, perhaps some early Q/A from the community. Speaking of which you are in the slack channel yes @davidkurutz ?

**Comment by davidkurutz** [comment]
@snuggs  Of course!  The slack channel is rubyonrails-link.slack.com? If so, just joined tonight.

**Comment by snuggs** [comment]
@davidkurutz be sure to reach out in introductions!

**Comment by davidkurutz** [comment]
@snuggs - here are some relevant links so you can get a preview.  Let me know when you have time to chat.

Thanks!

https://xorro-p2p.github.io/
https://davidkurutz.github.io

**Comment by snuggs** [comment]
hey @davidkurutz  can you update title to **[2017-10-10]** thanks!

**Comment by davidkurutz** [comment]
hey @snuggs  --- just checking in to confirm we are still on for 10/10 -- Let me know if you want to chat this week in prep.

**Comment by snuggs** [comment]
@davidkurutz https://www.meetup.com/preview/NYC-rb/events/ljjpglywnbnb
