### ISSUE TITLE
[2017-09-12] Building a Background Job Processor from scratch in Ruby

### ISSUE THREAD

**Issue by antoineLeclercq** [NYCrb/devpunks#38]
# Abstract
What is a background job processor? How does it work? Working with Rails, and using background job tools (such as Sidekiq) left me with these unanswered questions… As a remedy I decided to build one from scratch! What better way to learn and understand than by doing?

In my presentation I will talk about the following topics:
- building a background job processor from scratch
- working with concurrency and parallelism
- performance considerations of multithreading vs creating multiple processes
- what queueing system to use and why
- the different ruby implementations and their impact on such a tool

The project and the presentation are still in the works so I will be ready to present for the Meetup happening the 12th of September!

# Bio
Antoine is a Software Developer who mainly works with Ruby and JavaScript. He loves going by the ocean and ride on waves, whether it’s by surfing, kitesurfing or windsurfing. Oh, and he also fosters kittens from the ACC until they’re of age of being adopted!

@snuggs @brandondees

**Comment by snuggs** [comment]
@antoineLeclercq  ACCEPTED
