### ISSUE TITLE
[2017-09-12] Reflection in Ruby: Understanding The Implications of Loading Gems and Files

### ISSUE THREAD

**Issue by paulstefanort** [NYCrb/devpunks#39]
## Abstract
This talk describes ways to use Ruby’s reflection capabilities to analyze what is available in the runtime:

1. introduction to Ruby methods for detecting available classes and methods
2. detecting classes and methods made available by requiring a gem
3. detecting direct modification of existing behavior (via monkey-patching)
4. detecting indirect modification of existing behavior (module inclusion)
5. recommendations for further exploration of the topic

## Bio
Paul Stefan Ort is the lead engineer for [Dependable](https://www.dependable.io), a bot that automates dependency updates for Ruby applications.

**Comment by snuggs** [comment]
@paulstefanort would you be interested in giving this talk in September with @antoineLeclercq ? Here is his talk here. #38 . I want to make sure you get more than enough time as this is a great topic. Please advise. I am announcing tonight for next week's meetup. /cc @brandondees. If so can you please change to proper date and I can help you prep even more. Thanks.

**Comment by paulstefanort** [comment]
@snuggs Sounds good, I have updated the talk for September. Thank you!

**Comment by snuggs** [comment]
@paulstefanort  ACCEPTED!

**Comment by snuggs** [comment]
@paulstefanort @brandondees @pachonk  https://www.meetup.com/NYC-rb/events/235117573/?eventId=235117573
