### ISSUE TITLE
[2017-10-10] Building Ruby Bots on AWS Lambda

### ISSUE THREAD

**Issue by DamirSvrtan** [NYCrb/devpunks#40]
# Abstract

Want to build a Ruby Bot without the hassle of provisioning and managing servers? Amazon's got a service for that and it's called AWS Lambda - it executes your code only when needed, scales automatically and you pay only for the compute time you consume.

There's one problem with Lambda - it doesn't support Ruby!  
Let's checkout multiple options on how to build a Ruby Bot and package it into an executable which you can run on any machine without the need to actually have Ruby installed. We'll try three different flavours of Ruby in this lecture: mruby, jruby & travelling ruby.

# Bio

Damir is a Rails Team Lead at [Infinum](infinum.co), a software agency based in Croatia. He is a strong advocate of clean coding, automated testing and passionate about constant improvement. On top of that, he is an organizer of [Ruby Meetups](https://www.meetup.com/rubyzg/) in Zagreb, a regular blogger, open source lover and contributor.

cc @snuggs @brandondees

**Comment by snuggs** [comment]
now i got it @DamirSvrtan !!! :-) This is looking good! how's the slides coming?

**Comment by DamirSvrtan** [comment]
Hey @snuggs, I've got most of the slides ready, I just have to do a bit of rearranging. Do you need me to submit the slides somewhere?

**Comment by snuggs** [comment]
oh no worries. Just seeing if you needed any feedback. We can link before your show ;-) @DamirSvrtan

**Comment by DamirSvrtan** [comment]
No problem, we can post them prior if that's the way you work :) How far are we from getting this accepted? Do you need more info or modifications from my side @snuggs?

**Comment by snuggs** [comment]
Check labels @DamirSvrtan

**Comment by DamirSvrtan** [comment]
Awesome, thanks! Talk to you as the meetup date comes closer!

**Comment by snuggs** [comment]
@DamirSvrtan 🎉 https://www.meetup.com/preview/NYC-rb/events/ljjpglywnbnb

**Comment by DamirSvrtan** [comment]
Hey @snuggs, is there anything I need to know or bring before my presentation today?

I have a Macbook Pro with HDMI & mini display port, is that compatible with the stuff you have there?

Do you maybe have a presenter / clicker? 

I'm gonna be there around 6-6:30pm, is that okay or should I come sooner?

Thnx! :)
