### ISSUE TITLE
[2017-11-14] Replicate a production AWS environment on your laptop with Ruby

### ISSUE THREAD

**Issue by esilverberg** [NYCrb/devpunks#41]
# Abstract

Most applications developed today have dependencies on Cloud-based services like AWS S3, SQS or DynamoDB. When developing new code locally and/or writing unit tests in rspec, developers frequently are choosing one of two methods to accommodate these dependencies:

1) Writing conditional code to avoid contacting the production endpoint when the local environment is not set to 'production'
```
if ENV['RACK_ENV'] == 'test'
  // do not upload to S3
else
  // production code here
end
```

2) Creating a second AWS account, or uploading files to a test S3 bucket or test SQS queue or DynamoDB database, with a config file that contains the relevant AWS keys based on the environment.

The first method is undesirable because it pollutes production code with unnecessary conditionals, and prevents you from truly testing application logic end-to-end when writing tests.

The second method is undesirable because it costs money uploading test data, is slower if you are developing in a poor-connectivity areas like a subway or train, and requires you to periodically purge content out of your test buckets/accounts. It also requires you to potentially generate and check-in AWS secret keys locally on your dev machine to authorize operations against these cloud resources, when instead security best practices point to the extensive / exclusive use of instance-based IAM roles and no use of secret keys whatsoever.

SCRUFF has built a ruby library, [clientside_aws](https://github.com/perrystreetsoftware/clientside_aws/), that is integral to the way we develop and test one of the worlds largest gay dating apps, powered by Ruby and Sinatra. This library enables us to emulate at an API-level numerous AWS services, including [S3](https://aws.amazon.com/s3/), [DyanmoDB](https://aws.amazon.com/dynamodb/), and [SQS](https://aws.amazon.com/sqs/). We use this library in docker alongside dockerized versions of mysql, memcached and redis. Collectively, this approach enables SCRUFF to fully mock our production environment, locally on our laptops, and write new code in a zero-connectivity environment.

# Bio
Eric Silverberg is the CEO and primary architect of [SCRUFF](https://www.scruff.com), one of the largest gay dating apps worldwide with more than 12M+ users. Eric previously was an engineer at Microsoft, Product Manager at Google, and has an MBA from MIT Sloan and a Computer Science degree from Stanford.

/cc @snuggs @brandondees

**Comment by snuggs** [comment]
Lookin good @esilverberg !

**Comment by snuggs** [comment]
Oh man I wish you could give this talk yesterday. I NEED IT NOW! LOL @esilverberg! 💛

**Comment by esilverberg** [comment]
@snuggs haha thanks! Can share with you a short write-up (headline and summary) for your blast about the next ruby meetup before you send it?

**Comment by esilverberg** [comment]
OK here is my proposed blurb:

Title:

Code on a plane: Effectively mocking cloud AWS services for better development and testing

Description: 

If you require the Internet to develop and test your next ruby application, then your dev environment is broken!

Most applications developed today have dependencies on Cloud-based services like AWS S3, SQS or DynamoDB. When developing new code locally and/or writing unit tests in rspec, developers frequently are either using WebMock to send faked, static responses, or a test AWS account that gets polluted with dummy data over time. 

SCRUFF has built a ruby library, clientside_aws, that is integral to the way we develop and test one of the worlds largest gay dating apps, powered by Ruby and Sinatra. This library enables us to emulate at an API-level numerous AWS services, including S3, DyanmoDB, and SQS. We use this library in docker alongside dockerized versions of mysql, memcached and redis. Collectively, this approach enables SCRUFF to fully mock our production environment, locally on our laptops, and write new code in a zero-connectivity environment.

**Comment by snuggs** [comment]
Got it Can we announce? @esilverberg

**Comment by esilverberg** [comment]
Yes sounds good!
