### ISSUE TITLE
[2017-10-10] Introduction to concurrency in Ruby

### ISSUE THREAD

**Issue by thijsc** [NYCrb/devpunks#42]
# Abstract

Ruby is not considered to be a language that's great at concurrency, but actually we can build awesome concurrent software in Ruby. In this talk we'll build a minimalistic IRC-like chat server using three models; Multi-process, threading and an event loop.

During the process we'll look at how the these underlying mechanism in thee models actually work if you strip away the complexity. Also we'll see how the performance characteristics differ. At the end of the talk you'll have a good idea of how to use the main modes of concurrency in Ruby.

I've built a very simple implementation of the chat server in every model, which is available in a [public repo](https://github.com/thijsc/three-chat-servers). All versions are short and readable and serve both as the framework for the talk and as a great basis to do further exploring.

# Bio

Co-founder of AppSignal from Amsterdam, the Netherlands. Been programming in Ruby since discovering Rails when it was still in beta in 2005.

**Comment by snuggs** [comment]
@thijsc 🎉  https://www.meetup.com/preview/NYC-rb/events/ljjpglywnbnb

**Comment by thijsc** [comment]
Awesome!
