### ISSUE TITLE
[2017-11-14] Bindings in Ruby - behind the magic of blocks

### ISSUE THREAD

**Issue by esse** [NYCrb/devpunks#43]
# Abstract
> Why block can see local variables defined before him? Why can it change them? What kind of sorcery is this?

This is some kind of question that I will try to answer in my talk. We will see examples of blocks and hidden secret hero behind the magic - binding object.

In our magical journey, we will look into some Ruby code and some MRI/Rubinius/jRuby internals to help us better understand the magic. We will later use the new knowledge in practice to:

* understand erb
* understand binding.pry
* write our own openstruct-like implementation that stores data internally using local variables inside binding. In benchmark it's faster than openstruct, so yay us! ;)

Great magicians never reveal their secrets - but thankfully Ruby is open source, so we can lift the veil and see the real truth behind it. And believe me, it's quite beautiful!

# Bio
Piotr Szmielew is currently working at senior developer at [Rebased](http://rebased.pl). Working with Ruby and Rails since 2009, his secret hobby is diving into Ruby internals. Previously he worked in several Ruby companies, including preparing Ruby on Rails boot camp and mentor students in Coders Lab.

**Comment by snuggs** [comment]
Still would like to do @esse ?

**Comment by esse** [comment]
Unfortunately not, due to lack of feedback and info I'm not prepared.

W dniu śr., 8.11.2017 o 10:38 snuggs <notifications@github.com> napisał(a):

**Comment by dmitrinesterenko** [comment]
@esse would you like to give your talk in one of the upcoming NYCrbs? Our next one 02-13 may be too soon for you but we can do it in one of the next months. I'd like to schedule you in, I'm really excited about your topic.

**Comment by dmitrinesterenko** [comment]
@esse bump on this, any future dates you would want to talk about this at NYC.rb?
