### ISSUE TITLE
[2018-02-13] Runway overrun

### ISSUE THREAD

**Issue by samphippen** [NYCrb/devpunks#44]
@snuggs  asked me to file this issue for my talk :)

**Comment by dmitrinesterenko** [comment]
@samphippen great first step. Can you add an abstract of your talk ala the example here https://github.com/NYCrb/devpunks/issues/43

. 

You are set to present on 02/13?

**Comment by samphippen** [comment]
@dmitrinesterenko totally up for 02/13

## Abstract

Like it or not, failures in our production systems are inevitable. When things go wrong it's important for us to understand what happened, and more importantly why. In this talk I'll share personal experience and an outsiders' story. You'll learn a little bit about blame, about systems thinking, and how we can all get better at managing our failures.

## Bio

Sam Phippen is a Senior Engineer at DigitalOcean. He comes to the table with enthusiasm, and a great deal of love for the Ruby community. He fights for the forces of justice as a member of the RSpec core team. He's sad that he can't hug every cat.

**Comment by dstphantom** [comment]
@samphippen  Thanks for uploading the talk and adding the abstract.  We may need to push until March to have the second presenter confirmed @dmitrinesterenko.

**Comment by samphippen** [comment]
Can I get a confirmation on whether or not this is happening tomorrow?

**Comment by dmitrinesterenko** [comment]
@samphippen uploaded video of the talk https://www.youtube.com/watch?v=VoTcAgZSPqE
