### ISSUE TITLE
[Proposal 2018-04-10] A Webpack Survival Guide (for Rails Developers)

### ISSUE THREAD

**Issue by rossta** [NYCrb/devpunks#46]
Note: I'll be giving this talk at RailsConf on April 19

## Abstract

Perhaps you've thought about switching to Webpack now that it's an option for asset bundling in Rails 5. But your heart sank when you first opened a Webpack config file; it looked like an alien life-form. Maybe you've tried to get it working, but your old jQuery plugins won't even load in the browser and the docs were confusing.

Moving from Webpack basics to using it in production means understanding how it works. We'll demystify how Webpack bundles assets for the browser, how it differs from the Rails asset pipeline, and highlight common challenges that may occur coming from Sprockets.

We might not solve everyone's Webpack woes, but this is the talk I would have wanted to see before recently adopting Webpack in my team's Rails app at LearnZillion.

## Bio

Ross loves building things for the web and feels lucky to have been doing so for over ten years. He counts Webpack among his favorite topics to go along with Wes Anderson movies and long-distance triathlons.

**Comment by dmitrinesterenko** [comment]
@rossta Are you down to give this talk at NYC.rb in March? The date isn’t set yet so can play around around your schedule.

**Comment by rossta** [comment]
@dmitrinesterenko Thanks but I won't be available to do it in March.

**Comment by dmitrinesterenko** [comment]
@rossta cool, let us know what month works for you.

**Comment by dmitrinesterenko** [comment]
@rossta April 10th works for you?

**Comment by rossta** [comment]
@dmitrinesterenko Yes, that works for me. I'm targeting a talk length of 40min +/-5min. Will that work for you all?

Thanks, looking forward to it.

**Comment by dmitrinesterenko** [comment]
@rossta 👍
