### ISSUE TITLE
[Proposal 2018-03-28] Rails...Stil?!?!?

### ISSUE THREAD

**Issue by aspleenic** [NYCrb/devpunks#47]
Rails is amazing - from MVC to convention over configuration, Rails has helped start many businesses, launch many products, and gotten so many people into coding. But...are we missing something?

What about the alternatives? Trailblazer, Sinatra, Cuba, Volt, Lotus...even (gulp) Phoenix and Elixir?!?

This talk will take a look at when to use Rails and when it might be better to use an alternative. We will also talk about what those alternatives are and where they fit in in the Rails world.

**Comment by dmitrinesterenko** [comment]
@aspleenic can you do this talk in May? We have a scheduled NYC.rb date on May 8th but we can change that around still.

**Comment by aspleenic** [comment]
Hey Dmitri,

Unfortunately no - I’m at Malmö RB that night in Sweden.

**Comment by dmitrinesterenko** [comment]
@aspleenic Cool...any other days in May work for you?
