### ISSUE TITLE
[Talk Proposal 06/12] Command Line Applications in Ruby

### ISSUE THREAD

**Issue by keithrbennett** [NYCrb/devpunks#48]
Here's the pitch:

### Writing a Command Line Utility in Ruby - Automation is Not Just For Your Users

How many times have we dutifully repeated the same mouse and keyboard actions, missing the irony that we spend our lives automating things for others, but so often neglect to do so for ourselves?

This talk will walk you through the design and implementation of a wifi command line utility for the Mac – one that you could use as a model for automating your own manual process, including:

* the multitude of cost/benefit decisions, including many compromises for speedier completion.
* command suite (e.g. git) vs. option based (e.g. grep) design
* how to address a target audience that includes non-Rubyists
* class design, including separating back end functionality from command line & user input plumbing, and multi-OS support
* providing an interactive shell in your utility

After this presentation you will be able to make a better informed decision about the optimal balance of effort and functionality, and be better equipped to write an excellent implementation.

----

The command line application that inspired this presentation is `wifi-wand`, which provides a simplified interface for WiFi operations on Mac OS. You can `gem install` it, and/or check out the Github project page at https://github.com/keithrbennett/wifiwand.

I just presented this talk at the Baltimore Rails group a couple of days ago, and at RubyConf Philippines in March, and will present it in Paris in late June at Paris.rb Conf. The slide show of the Baltimore presentation is at https://speakerdeck.com/keithrbennett/command-line-apps-in-ruby-2018-05-08 and the YouTube video of the Philippines presentation is at https://www.youtube.com/watch?v=82lm3sRECrg. (The presentation has been improved since then.) The talk's optimal length is 45 minutes.

Optimal presentation date would be the June meeting; I may be returning to Thailand after the Paris conference in late June.

**Comment by dmitrinesterenko** [comment]
@keithrbennett great talk, looking forward to it. Does June 12th work for you?

**Comment by keithrbennett** [comment]
Yes, June 12th would be great.

Questions:

* 7:00, right? 
* Could I get 45 minutes for the presentation?
* I have a 2015 MacBook Pro with HDMI port. Will I need an adapter for your projector?
* Is there power available close to the presenting area in case I run the battery low coworking before the meeting?
* Is the location XO Group, 195 Broadway, 24th Floor, New York, NY 10007 · New York, NY

Looking forward to it!

**Comment by dmitrinesterenko** [comment]
@keithrbennett 
* yes the talks start at 7PM. 
* You can have 45 minutes.
* We use Zoom.us to project content, it has worked really well and allows us to record the Meetup content easily.  You don't need any cables for that.
* We have power available right at the table we use to place speaker laptops
* That is the location

**Comment by keithrbennett** [comment]
Great, I will see you then!

**Comment by keithrbennett** [comment]
Is it ok to have people not at the meeting join the Zoom meeting so they can watch/listen remotely? Do you publicize the URL of the meeting, and/or is it ok for me to do that? (Also, am I correct in assuming I won't know the meeting URL until I "start" the Zoom meeting?) Or do you have a fixed URL that will dynamically redirect to each meeting's Zoom URL?

**Comment by dmitrinesterenko** [comment]
@keithrbennett (Yes if they are not in NYC, if they are they should just come on down :) :) . I think I can generate a Zoom link ahead of time, I use the same Zoom link in at least one of my meetings, I'll do that Monday. It will be OK to publicize it.

**Comment by dmitrinesterenko** [comment]
@keithrbennett this is the Zoom link that I am having us host this meetup on https://zoom.us/j/328899952

**Comment by dmitrinesterenko** [comment]
Meet up description set https://www.meetup.com/NYC-rb/events/vvjrrpyxjbqb/

**Comment by keithrbennett** [comment]
Dmitri and all -

Greetings!

I was thinking of getting dinner before the meeting, but it occurred to me
that you might have food at the meetup. Do you?

Also, do you use a microphone, and, if so, is there any way to connect my
Mac's sound output into your sound system mixed with the mic?

Thanks,
Keith


On Thu, May 31, 2018 at 2:10 PM, Dmitri Nesterenko <notifications@github.com

**Comment by snuggs** [comment]
@keithrbennett yes @dmitrinesterenko is out of the hemisphere ATM until later this week. But the 🍕  was delish! ;-)
