### ISSUE TITLE
[Talk Proposal] Developing Security Features with MessageEncryptor and MessageVerifier

### ISSUE THREAD

**Issue by mjc-gh** [NYCrb/devpunks#51]
I would like to do a security minded talk about [MessageEncryptor](https://api.rubyonrails.org/v5.2.1/classes/ActiveSupport/MessageEncryptor.html) and [MessageVerifer](https://api.rubyonrails.org/v5.2.1/classes/ActiveSupport/MessageVerifer.html). This talk will cover:

1. An overview of these two classes, how they work, and what they provide for. I will explore the difference between encrypting and signing a message and the security guarantees these two classes provide. I'll also showcase some the latest features of these classes including the new [metadata features](https://medium.com/@michaeljcoyne/rails-5-2-metadata-options-for-messageverifier-and-messageencryptor-79540de86f9b).
2. Next I'll show how we at Knotch used `MessageEncryptor` to build a more robust authentication and authorization system for our [Sidekiq Enterprise Web UI](https://github.com/mperham/sidekiq/wiki/Ent-Web-UI#authorization).
3. Lastly, we'll explore other features that could be implemented using these classes including "remember be" login cookies and signed, self-expiring URLs for resource downloads.

**Comment by mikeycgto** [comment]
I'm very flexible on dates if this talk were to be accepted. Thanks!

**Comment by dmitrinesterenko** [comment]
@mikeycgto this talk is perfect. You're confrimed for October 9th. Does that date work for you?

**Comment by mikeycgto** [comment]
@dmitrinesterenko sounds great! I'm looking forward to it!!

**Comment by 7urkm3n** [comment]
Hi @mikeycgto, is there way to see the presented slideshows online?

**Comment by snuggs** [comment]
#ping @mikeycgto

**Comment by mikeycgto** [comment]
Apologizes @snuggs and @7urkm3n, here are my slides: https://www.dropbox.com/s/lsxxfghfxbaa6nn/NYC-Ruby-Oct-Security-Talk.key?dl=0
