### ISSUE TITLE
[Talk Proposal] How to make your code faster with Multithreading

### ISSUE THREAD

**Issue by sunny-b** [NYCrb/devpunks#52]
It's a fairly simple talk idea but it's an interesting topic. This is an introductory talk that covers the basics and fundamentals of threads, multithreading, and concurrency. The concepts that it will cover are:

- Concurrency vs. Parallelism
- Processes vs. Threads
- How to use multithreading to speed up your code
  - Thread safety
  - Race Conditions
  - Mutex

I will finish with a demo that's inspired by a recent task where I had to create a low latency API for my job at DigitalOcean.

This talk will be a visual presentation of a [Medium post I made recently](https://hackernoon.com/need-faster-code-try-multithreading-5dc30c83837c).

Edit: I recently presented this talk to an online forum and had it recorded. You can see it for yourself and judge if it will be appropriate for this Meetup (https://dkq85ftleqhzg.cloudfront.net/tech_talks/multithreading_and_rubys_thread_class.mp4)

**Comment by SpencerTang** [comment]
Hi @sunny-b this talk looks great! Would love to have you present your talk at NYC.rb, what date were you looking at to give the talk?

**Comment by sunny-b** [comment]
Hey @SpencerTang ! I'm not very picky on the date. Anytime in November or December would be fine. I see that NYC.rb has a meetup scheduled for Nov. 13. I can do that date if the speaking positions haven't filled up yet.

**Comment by SpencerTang** [comment]
Hey @sunny-b we already have some speakers lined up for November but would love for you to present at our next one on 12/11 if that works for you.

**Comment by sunny-b** [comment]
Yep, that works as well!

**Comment by SpencerTang** [comment]
@sunny-b sorry to hear that would you be available for a talk on 1/8?

**Comment by sunny-b** [comment]
Yeah I can do that!

**Comment by SpencerTang** [comment]
Awesome sorry again about the reschedule, looking forward to meeting you on 1/8!

**Comment by dmitrinesterenko** [comment]
@sunny-b your talk is on this video https://www.youtube.com/watch?v=YlJlCfUGasc&feature=youtu.be
