### ISSUE TITLE
[Talk Proposal] How to create user sign ups and logins with the BCrypt gem

### ISSUE THREAD

**Issue by Mewtwo2** [NYCrb/devpunks#53]
With the onslaught of security breaches left and right, I believe it is very important to keep sensitive user data hashed so that attackers do not have access to everything if they succeed in penetrating the database. The talk would be about basic user sign up and login using BCrypt in rails to hash passwords.

- How to create simple user sign up and login

- How to install Bcrypt gem and use BCrypt syntax to hash user passwords

- How to utilize sessions in rails to store and retrieve users

- How to use helper methods to manipulate views and user sessions

- How to authenticate using BCrypt

**Comment by SpencerTang** [comment]
@Mewtwo2 thanks for submitting your talk and sorry for the delayed response! When would you be available to speak?

**Comment by Mewtwo2** [comment]
@SpencerTang No problem, I would be available to talk any time in January or the months after.

**Comment by SpencerTang** [comment]
Sounds good I have scheduled you for 1/8!

**Comment by Mewtwo2** [comment]
Thank you, I look forward to it

**Comment by dmitrinesterenko** [comment]
@Mewtwo2 we have the second half of your talk here: https://www.youtube.com/watch?v=YlJlCfUGasc, the recording was turned on late.
