### ISSUE TITLE
[Talk Proposal] Machine Learning in Ruby (and Only Ruby)

### ISSUE THREAD

**Issue by toddsundsted** [NYCrb/devpunks#54]
I didn't see this in any of the historical pitches, so...

An introduction to mxnet.rb (https://github.com/mrkn/mxnet.rb), Ruby bindings for MXNet (https://mxnet.incubator.apache.org/), a full-featured framework for machine-learning. The talk will focus on my implementation of the Gluon interface (a high-level library of neural network building blocks) that is being integrated into mxnet.rb, with demonstrations on how it can be used to implement the examples in the excellent MXNet tutorial, The Straight Dope.

Mxnet.rb is important because it brings a well designed numeric array datatype to Ruby (important for many kinds of numeric computing) *along with* a state of the art machine learning framework. No more diving into Python in order to learn or use machine learning.

**Comment by SpencerTang** [comment]
@toddsundsted sorry for the delayed response! This looks like a really interesting talk! When would you be available for the talk?

**Comment by SpencerTang** [comment]
Amazing you are scheduled for 2/12!

**Comment by toddsundsted** [comment]
Confirmed!
