### ISSUE TITLE
[Talk Proposal] Learn You Some Kafka: Interactive tutorials that teach how to work with Kafka in Ruby

### ISSUE THREAD

**Issue by aviflax** [NYCrb/devpunks#55]
Hi, I’ve not yet managed to make it to a meetup yet, being based in Westchester, but I do dabble in Ruby and I’ve been hoping to attend some time.

[Learn You Some Kafka](https://github.com/FundingCircle/learn-you-some-kafka) is a FLOSS project I’ve been working on within [Funding Circle](https://fundingcircle.com) because we have a bunch of Rubyists and we are gradually shifting many of our systems to use [Kafka](http://kafka.apache.org) as their primary datastore and/or for data integration.

The project currently has 2 CRuby units with 7 total lessons; our JRuby curriculum is lagging behind a bit but should achieve parity within a week or two. So far I’ve received positive feedback on the tutorials from within Funding Circle.

I think what’s most interesting about this is:

1. The fact that it exists
   * I suspect that there are many Rubyists in the world who would find this useful, but don’t know it exists. So I’d like to try to publicize it a bit.
2. The interactive and concrete nature of the lessons
   * I should make a screencast or a shell-gif or something, but anyway, basically the lessons run in Docker and they work by showing you a bit of code, then running that code and showing the results. So you get to see and run small, short snippets of real code that’s doing real work, and see the output.

I haven’t yet prepared an actual talk on this but I’ve got plenty of experience with that sort of thing so I’m confident I could come up with something half-decent pretty quickly.

One of the reasons I haven’t prepared the talk yet is that there are a bunch of different directions I could take it. I could focus on:

* the specific content of the lessons
  * i.e. I could _use_ the lessons to try to actually teach their contents in the session
* the interactive and concrete format of the lessons (why, how)
* the story of the project: how and why it came to be and came to take the shape it’s in

Or if desired I could touch on all of those as a sort of a case study. A case study in… finding a way to teach something new and concrete to a specific developer population, I guess.

Sorry, my point is, I’d welcome any guidance or suggestions that the organizers would be able to provide, to make this talk more relevant and appropriate to NYC.rb in 1H-2019.

----

Ah, and in my correspondence with @dmitrinesterenko he asked me to provide some specific information:

### Ruby/programming skills required

* The project and its code assume basic proficiency with Ruby. Nothing too esoteric is used, and no frameworks, so a basic understanding of syntax, functions, blocks, variables, and objects should suffice. That said, while I’m presenting I’ll be careful to explain anything particularly advanced I might have used in the code.
* The project and its code assume familiarity with Kafka — what it is, what it’s for, and its basic concepts. For the talk though, I’d be happy to start with a quick 3–5 minute introduction that should suffice for understanding the tutorial demo and code.

### Length of time you think you need

Since I haven’t prepared the talk yet, I’m flexible on this. I could squeeze it into a 10-minute lightning talk or go deep and take ~40 minutes if so desired. If I have ~30+ minutes then I could spend a little time talking about the interactive format of the lessons, and how and why I came up with it, and how its implemented.

### Any special equipment needed

Nope.

----

Thanks!

**Comment by SpencerTang** [comment]
@aviflax this proposal looks fantastic! When are you available to speak? We have an opening on 2/12 and 3/12

**Comment by aviflax** [comment]
Thanks! Either of those dates should work. I’ll confirm on Monday. Have a great weekend!

**Comment by aviflax** [comment]
Yeah, looks like either date should work for me. However, I still haven’t managed to make it to a meetup, so the March date might be a little better, so I can try to make the Feb meeting and maybe be a little less of a flyby. Up to you though. Thanks!

**Comment by SpencerTang** [comment]
March it is, you are confirmed for 3/12!

**Comment by aviflax** [comment]
Thanks @SpencerTang I’m excited! I just need a day or two to confirm, I’ve also been asked to speak at the early March Clojure meetup in London, which is organized and hosted by my employer, so I’m trying to get that date finalized to ensure there’s no conflicts. I will be in touch within a day or two.

**Comment by SpencerTang** [comment]
No worries, keep me posted and best of luck with the other talk!

**Comment by aviflax** [comment]
3/12 is looking better for me if that’s OK. If you’re short on content for 2/12 I can probably swing that too, but honestly I’d feel a little funny dropping in to the meetup for the first time ever with a talk 😬

**Comment by SpencerTang** [comment]
3/12 it is! Looking forward to meeting you on 2/12 as well.

**Comment by aviflax** [comment]
Great! Thanks!
