### ISSUE TITLE
[Talk Proposal] Debug Hard: Ruby String Library Methods and Underlying C Implementations

### ISSUE THREAD

**Issue by vchandnani-zz** [NYCrb/devpunks#56]
Hello,

Happy New Year! I recently joined NYC.rb.

At this time, the Ruby String library 'reverse' method is fairly stable. However, what if the underlying C implementation had a bug? What if it produced unexpected results with certain types of inputs? e.g. strings with unicode characters. How would you catch and fix such a bug? How would you explain the unexpected results?

In this talk, we'll take a close look at how Ruby's String library 'reverse' method works. In order to catch a potential underlying bug in this method, we need to understand its implementation. Where exactly is the source code? Does it have adequate unit tests? Put on your debugger hats and join me explore some powerful techniques to isolate and fix such bugs. This talk will add value to your debugging tool belt and improve your confidence in finding/fixing problems that lay underneath the current (Ruby) application programming language.

Please note, I presented the following related 5-minute lightning talks at work:

1. C versus Ruby String Reversals
2. Debugging Ruby String Library Methods

This proposal for the meetup talk includes some ideas/materials from the above lightning talks, with the addition of unicode characters. I'm excited to share my learning experiences and get feedback from our community.

I look forward to hearing from you soon!

Best,
Vishal
LinkedIn: https://www.linkedin.com/in/vchandnani/

**Comment by vchandnani** [comment]
@SpencerTang Thanks! I would prefer 3/12.

**Comment by vchandnani** [comment]
@SpencerTang Just checking in, are we on for Tuesday 3/12?

**Comment by SpencerTang** [comment]
@vchandnani sure thing, you are confirmed for 3/12!

**Comment by vchandnani** [comment]
@SpencerTang Great, thanks!

**Comment by vchandnani** [comment]
@SpencerTang @dmitrinesterenko Just checking in, are we good for April (4/9) or May (5/14)?

**Comment by SpencerTang** [comment]
@vchandnani no worries, 4/9 works for us!

**Comment by vchandnani** [comment]
@SpencerTang @dmitrinesterenko Thanks! I plan to attend Tuesday, 3/12 (gives me a chance to check out the venue) and will be ready to speak Tuesday, 4/9. See you soon.
