### ISSUE TITLE
[Talk Proposal] The DRY Principle Is Misunderstood

### ISSUE THREAD

**Issue by steven-solomon** [NYCrb/devpunks#57]
### Abstract:
You have probably heard of the DRY Principle, but what you don’t know is that it has nothing to do with duplicate code. Join Steven Solomon as he teaches you to re-think the DRY Principle, how to identify incorrectly “DRY” code, and how to refactor your code so that it is easy to change again.

### Description
The Don’t Repeat Yourself Principle has swept the world, it is often the first thing new engineers are taught. It has probably affected your current code base in a big way. However, despite your code being “DRY”, your code is hard to change. The same files have to be changed over and over for seemingly unrelated reasons, and code brittleness due to tight coupling abound. You might ask yourself, “Why is this happening?”

In this talk I will teach listeners that the DRY Principle is actually about eliminating duplicate representations of ideas not duplicate code. Duplicate code is often misidentified as part of this principle, and attempts to clean it up are made. The end result is lots of divergent change (one place changes for many reasons), yielding tons of pain for the development team, and eventually a clamor for a complete rewrite of the system.

This talk begins with a story about how removing code duplication caused a team to become stuck with a tightly coupled mess.

Then I will tell the listeners three techniques to identify incorrectly DRY code:

- Focused conversations with the product team
- Asking yourself the question “can I reason about this separately?” before you remove duplication
- How to notice Divergent Change

Once the listener knows how to identify incorrectly DRY code, I will walk them through a code example where introducing a new path is very difficult. We will refactoring the code so that the independent concepts are isolated. Once the code is fixed, I will show how easy it is to make the desired change.

### About the Author
Hi, my name is Steven Solomon, I am a Lead Engineer at Stride Consulting. 
I have spent about 10 years writing software on teams in many industries and languages.
I am very passionate about writing clean code and I want to share my experiences with you, if that doesn't work I'll play you some blues guitar.

You can check me out on twitter: [@ssolo112](https://twitter.com/ssolo112), or on medium [@ssolomon](https://medium.com/@ssolomon)
### Notes
I have given this talk to 40+ people at the Pivotal Labs office in NY (where I work). I am scheduled to give this talk in March at [Boston Ruby](https://www.meetup.com/bostonrb/events/258872786/), and in May during Saturn 2019 at Carnegie Mellon.

**Comment by SpencerTang** [comment]
@steven-solomon this looks great! When were you thinking of presenting? We have an opening in May on the 14th.

**Comment by steven-solomon** [comment]
@SpencerTang I am open to presenting in April as well, but let's schedule for May 14th.

**Comment by SpencerTang** [comment]
@steven-solomon unfortunately we had to cancel the event for May due to logistical reasons. We would still love for you to do the talk. Would it be possible for you to reschedule and speak at the next meetup on 6/11? Really sorry for any inconvenience this may have caused.

**Comment by steven-solomon** [comment]
@SpencerTang No worries. Yes I am available on 6/11. I'm very excited to share my experiences with the NYC Ruby community.

**Comment by SpencerTang** [comment]
@steven-solomon awesome, I have scheduled you for 6/11 sorry again about the inconvenience!

**Comment by SpencerTang** [comment]
@steven-solomon yes it will be recorded however we don't have any photos planned.

**Comment by steven-solomon** [comment]
That’s awesome, would it be possible to get a copy of that?

**Comment by steven-solomon** [comment]
Thank you again for the opportunity to speak with such an great group! 

Would it be possible to get a copy of the recording of that evenings talks?

**Comment by SpencerTang** [comment]
@steven-solomon sorry for the delayed response, since I no longer work at XO Group I've been trying to get a copy of the recording. Unfortunately the team couldn't find the recording from the MeetUp. Sorry for any inconvenience!
