### ISSUE TITLE
[Talk Proposal] Lets Make a Ruby Microservice via AWS Lambda

### ISSUE THREAD

**Issue by MichaelGarrigan** [NYCrb/devpunks#58]
Hey NYCrb,

This past November AWS added a Ruby 2.5 environment for the lambda platform and is now on its 3rd version of its Ruby SDK that came out in 2011. For this proposed talk I would like to go through the steps of deploying a Ruby Microservice on AWS.

The items to be covered: 
- General microservice architecture.
- How to observe/monitor events that can set to trigger our Ruby function.
- Where do the logs go?
- Continuous Integration & Continuous Development Strategies for AWS Lambda.
- How to communicate with other services?
- Security groups and secure users.
- Testing our lambda function.

As of now I would expect a talk like this would be rather large 30 - 40 minutes, and I am comfortable to speak at this length. But I can definitely slim this down if it is preferable to fit within a different time slot.

I do not think the material would be ready for the April meetup but it can be easily put together for May. 

Thank you for the consideration,

Michael Garrigan
https://www.linkedin.com/in/mgarrigan/

**Comment by SpencerTang** [comment]
Very cool idea for a talk, love Serverless! How does 6/11 look for you?

**Comment by M-garrigan** [comment]
Yeah 6/11 sounds good. See you next meetup.

**Comment by SpencerTang** [comment]
Awesome you're scheduled for 6/11!

**Comment by snuggs** [comment]
This talk sounds dope @M-garrigan
