### ISSUE TITLE
[Talk Proposal] Hyperstack - A new way to build React Apps In Ruby

### ISSUE THREAD

**Issue by catmando** [NYCrb/devpunks#59]
Hi, I am not from NYC, but I need to often come down for business reasons.

I would love to do a presentation on a Rails gem that I am one of the lead contributors on, and that my company uses in production.

The gem is called `rails-hyperstack` and you can find out more about it here: https://hyperstack.org  I also just posted a quick video on it here: https://www.youtube.com/watch?v=GEe7hHIhyUs .

We are getting very close to our 1.0 release, and it would really help us to get as much feedback as possible, before we lock things down.

As you will see in the video its really pretty cool.  I know I am biased but how about:
- write all your code (including the FE stuff) in Ruby
- a really nice DSL so you don't have to deal with JSX
- access your Active Record models directly on the client *(yes its true)*
- a far easier to use React state management system
- direct access from Ruby to 3rd party JS component libraries
- resulting code runs about 1/4 the SLOC as JSX + Rails BE counterparts
- built-in pre-rendering so on page load HTML is delivered directly to the client
- sophisticated policy based data access controls
- code edits instantly update the browser
- `rspec` extensions so you can use one testing environment end to end
- works equally well with clean sheet or existing Rails apps

I would be happy to do a presentation as short or as long as you like, and either as lecture or a hands on "lets build an app" style.

**Comment by SpencerTang** [comment]
@catmando love the idea for the talk does 8/13 work for you?

**Comment by catmando** [comment]
@SpencerTang - man sorry, I didn't see the response till just now.  At any rate I am out of town then.  Hopefully we can find another date in the coming months.  Again sorry for the delayed response.

**Comment by SpencerTang** [comment]
@catmando no worries, let me know when you're available and we will be happy to schedule you!

**Comment by catmando** [comment]
Looks like I can do any of the following Tuesday meetings (sept/oct/nov) My pref would be the October meetup.
