### ISSUE TITLE
A way for beginners to jump in and collaborate on real-world projects

### ISSUE THREAD

**Issue by arku** [NYCrb/devpunks#6]
Of course we have github, which lets anyone collaborate on a open source project but often times, it is intimidating for a beginner to jump in. I guess we need a medium to atleast point beginners to the right project, to kick of their open source contributions. Or even better, let the beginners brainstorm and find problems that can be addressed with web applications. Once we have some project ideas, form teams and start hacking on projects. 

/cc @snuggs

**Comment by snuggs** [comment]
👍  @arun1595
