### ISSUE TITLE
[Talk Proposal] My (Ruby Related) Dotfiles

### ISSUE THREAD

**Issue by sshaw** [NYCrb/devpunks#61]
A presentation on Ruby related things I have in my dotfiles: https://github.com/sshaw/dotfiles

**Comment by SpencerTang** [comment]
@sshaw thanks for submitting a talk! Could you provide additional details regarding the talk? You can use one of our previous talk description as an example here https://github.com/NYCrb/devpunks/issues/57.

**Comment by sshaw** [comment]
I can send you close-to-but-still-incomplete version of the presentation. Just tell me where.
