### ISSUE TITLE
[Talk Proposal](Lightning talk) Rollout features with confidence!

### ISSUE THREAD

**Issue by yodarjun** [NYCrb/devpunks#62]
Hey fellow NYCrbers,

Recently I had to work on a project that was relatively large in a critical part of our system. I didn't want to do a long waterfall-ey process for developing the feature just to roll it out to production in one fell swoop. So instead, I came up with a simple way to rollout the feature to production eventually while having the ability to iteratively build the feature in my dev environment as well as deploy it knowing that it wont hurt production until it was fully ready to go.

So in this talk, I would like to go over:
* The strategy I used
* Where this strategy can be useful
* Where this strategy would need some more work

I dont think I have enough material in this talk for a full length one so I'd like to present this as a lightning talk.

Thanks.
~Arjun

**Comment by dmitrinesterenko-penguinpay** [comment]
[rollout features with confidence.pdf](https://github.com/NYCrb/devpunks/files/3628842/rollout.features.with.confidence.pdf)
