### ISSUE TITLE
[Talk Proposal] WebAuthn in Ruby

### ISSUE THREAD

**Issue by brauliomartinezlm** [NYCrb/devpunks#63]
Hi NYC.rb!

@grzuy and I are going to be in NYC the week of Nov 10th and we realized of the Nov. 13th meetup. We’d like to propose a talk about WebAuthn.

We have been working on [WebAuhtn’s server gem](https://github.com/cedarcode/webauthn-ruby) for the last year and a half. [WebAuthn](https://www.w3.org/TR/webauthn/) has been gaining adopters at a good pace in the last year, specially after it became an official recommendation in March this year and some big companies started working on adding it to their systems.

The preparation of this talk already in progress but still on an early stage, some things can change a bit, but the high level topics we would like to go through would be:

- What is WebAuthn?
    - what is it?
    - when/who created it?
    - what process it followed?
- What is the motivation to create a standard like WebAuthn?
- How does it work?
    - architecture description
    - different ceremonies for registration/authentication
    - more (this is probably the heaviest high level topic)
- WebAuthn in Ruby
    - readme content
    - some internals
    - what it does
    - compatibility
    - FIDO conformance tools
- Demo (About 5 mins)(webauthn.cedarcode.com)
  - show different flows (registration/authentication) in action
  - show different authenticator devices on a computer
- Adoption
    - Ruby based well-known apps that adopted the standard and how
    - what are the challenges
    - full password-less vs 2FA
- How can I migrate to a WebAuthn based authentication?(Open source case studies)
    - Rubygems.org
    - our demo app
    - Login.gov
- What are we working on next?
    - next steps for the gem
    - collaboration to OSS to help adoption and add security to more real-life heavily used apps
    - related gems we want to build
- Leave resources for the talk attendees to be able to followup easily from the slides and dig deeper on WebAuthn and encourage them to take the step.

This talk duration we think can go from 20 - 30 mins (we’re still unsure as it’s a WIP), plus Q&A. Maybe could take a little more now that I see all the topics I've listed 😄😄, we'll definitely keep it below 40mins and scope it down if we're required.  

We would really appreciate any feedback and would love to share more in depth details if necessary.

Thank you!!

**Comment by dmitrinesterenko** [comment]
@brauliomartinezlm 👍

**Comment by chazelton331** [comment]
Hey @brauliomartinezlm! Looking forward to hearing this talk. I'm organizing this Meetup event, which is at the Stash office. Can you email me (cliff [at] stashinvest.com) so we can coordinate?
