### ISSUE TITLE
[Talk Proposal] You're already doing TDD

### ISSUE THREAD

**Issue by Trevoke** [NYCrb/devpunks#64]
Hi NYC.rb!

I'm a Stasher and I'd like to propose a talk for the November 13th meetup. The talk is "You're already doing TDD".

This talk would be about 15 minutes (could easily be longer, but we already have a long talk for that day).

TDD is a polarizing topic. The acronym has at least two meanings (is it Design or Development?), it has spawned at least one other technique (BDD), and it's rarely clear what it is, what it isn't, and what it means to "do TDD".

The talk would cover the problem-solving flow that we follow when writing code (take big problem, break it down into smaller, more manageable problems, solve smaller problems, connect them together and big problem is solved). It would relate this to [Fermi questions](https://en.wikipedia.org/wiki/Fermi_problem) as a formalized example of that thought process, then move on to TDD. The talk would remind the audience that TDD is a tool and therefore can be leveraged as we wish, then describe the steps of the TDD process, how they map to the problem-solving flow shown earlier, and how they can be leveraged for specific purposes.

The talk would conclude that TDD is fundamentally a simple idea standing on the shoulders of giants, a flexible practice, and a powerful tool. It's not magic, and it doesn't change the way you think. It's just a tool -- and while great craftsmen don't blame their tools, great craftsmen do learn how and when to use them. So, the talk would end with a recommendation to take a little time and get familiar with the tool.

Things to try mentioned at the end of the talk:
- exercism (lightweight: tests already exist)
- http://ruby-challenge.rubylearning.com/ (lightish weight, self-contained, some have a test suite, some don't)
- Moss' tiny projects blog entry: http://makingcodespeak.com/2014/04/18/tiny-projects.html (lots of ideas for self-contained projects)

And, depending on time left, either a Q&A or a "@ me after the talk" slide.

**Comment by chazelton331** [comment]
@Trevoke accepted! I'll reach out to coordinate and to add an abstract to the Meetup event page.
