### ISSUE TITLE
Update Punk Mission Statement Copy

### ISSUE THREAD

**Issue by snuggs** [NYCrb/devpunks#7]
Update copy on mission statement to align with Punk Subculture

https://en.wikipedia.org/wiki/Punk_subculture

**Comment by btakita** [comment]
Fight the Technocracy!

**Comment by snuggs** [comment]
Fuck yeah this is awesome @btakita

**Comment by snuggs** [comment]
Link to how to use quotes properly in HTML5 http://html5doctor.com/blockquote-q-cite/

**Comment by snuggs** [comment]
- http://www.nycnode.com
- http://kickass-consulting.com
- https://tympanus.net/Development/CreativeLinkEffects/#cl-effect-1
