### ISSUE TITLE
[Talk Proposal] How Prime Numbers Keep the Internet Secure

### ISSUE THREAD

**Issue by sunny-b** [NYCrb/devpunks#70]
# Title

How Prime Numbers Keep the Internet Secure

# Abstract

While many software engineers don’t work directly with prime numbers on a daily basis, they play a crucial role in keeping your web applications secure in the form of Hypertext Transfer Protocol Secure (HTTPS).

In this talk, you will learn the inner workings of how HTTPS uses prime numbers to keep your data private as it travels over the internet. We will cover topics such as symmetric and asymmetric encryption, and why prime numbers are just so damn hard to crack. By the end, you will understand how to encrypt and decrypt data yourself with Rails and the Ruby standard library.

So come join me as we demystify HTTPS using code, color theory, and only a pinch of math 🤓.

# Details

This talk is a beginner-friendly introduction to cryptography and HTTPS. It is targeted at beginner and intermediate engineers who work on web applications.

The presentation will begin with an introduction to HTTPS and how it is used to secure data as it travels across the internet. This will lead to an introduction and description of asymmetric and symmetric encryption. Visuals and color theory will be used to core aspects of encryption and decryption. I will focus on the RSA algorithm to demonstrate public and private key generation. This is where the power of prime numbers will be on full display as I describe how prime numbers ensure that the RSA algorithm is secure. The presentation will conclude with code samples demonstrating how to implement RSA encryption and HTTPS.

By the end, the audience will understand how simple concepts like prime numbers and the modulo operator can be used to ensure data privacy. They leave knowing how to implement asymmetric encryption and decryption themselves using Rails and the Ruby standard library.

# Pitch

In an age where data breaches are on the rise, cryptography and data security are becoming a more necessary skill. As web developers building software on the web, it is important to understand how data travels securely between their application to their users. Unfortunately, cryptography can appear math-intensive and intimidating to beginners. As a novice cryptographer myself, I understand the frustration of wanting to learn a new subject only to be confronted with math equations that fly over my head.

While math is unavoidable in cryptography, I explain all the concepts using easy to understand analogies and visuals. I also use simple and jargon-free language since I don’t understand the jargon myself. Furthermore, by showing the audience the steps to recreating RSA and HTTPS, I want to make cryptography more approachable and give the listeners a headstart into exploring the field of data security.

**Comment by dmitrinesterenko** [comment]
@sunny-b are you availble to give this talk virtually on June 10th at 5:30-ish PM?

**Comment by sunny-b** [comment]
Right now isn't the best time for me unfortunately, I'm rather busy at the moment but hopefully I'll be more free in the future.

**Comment by notable-dmitri** [comment]
@sunny-b got it, thank you.

**Comment by dmitrinesterenko** [comment]
@sunny-b heya, do you have availability to give this talk in our online meetup in the next couple of months? We would be happy to host you.

**Comment by dmitrinesterenko** [comment]
@sunny-b any interest in presenting that talk in 2021? Would be good to start the year off with some better appreciation for security.

**Comment by sunny-b** [comment]
Sorry, I'm expecting my first kid in January 2021 so I'm going to be pretty busy lol.
