### ISSUE TITLE
[Talk Proposal] StrictMoney: Value objects in practice

### ISSUE THREAD

**Issue by fhwang** [NYCrb/devpunks#71]
# Abstract

Value objects are small immutable objects where equality is not based on identity. I recently made use of this pattern with a gem called StrictMoney, which treats financial amounts as values that support specific mathematical operations, while also preventing programmers from accidentally using the wrong currency and creating difficult-to-trace bugs.

Using StrictMoney as an example, I'll walk us through a number of topics around object design and Ruby, including:

- When to define your own value object
- Value objects' role in enforcing architectural principles
- The good and bad of object mutability
- Ruby's power and expressiveness in defining value objects

# Bio

Francis Hwang is the founder of NYC.rb and co-founder of Gotham Ruby Conference.  These days he is an independent software consultant specializing in software architecture, organizational process, and observability.

**Comment by snuggs** [comment]
@fhwang good to see you here! :-) talk looks awesome.

**Comment by dmitrinesterenko** [comment]
@fhwang can you speak at the June 10th meetup? 5:30-ish to start.

**Comment by fhwang** [comment]
Sure thing!

**Comment by dmitrinesterenko** [comment]
@fhwang you're on!
