### ISSUE TITLE
[Talk Proposal] The Bug that Forced Me to Understand Memory Compaction

### ISSUE THREAD

**Issue by egiurleo** [NYCrb/devpunks#74]
Hello! I hope you're all doing well and staying safe. I'm not sure if you're still doing online meetups, but if you are, I'd love to give a talk I've been working on about memory compaction in Ruby MRI 2.7.

## Abstract

Did you know that Ruby 2.7 introduces a new method for manual memory compaction? 

Neither did I. 

Then a user reported a bug on a gem I maintain, and well...

In this talk, I’ll tell you a story about how one bug forced me to learn all about memory management in Ruby. By the end of this talk, you should understand how memory is allocated on the heap, how Ruby implements garbage collection, and what memory compaction is all about!

## Details

This talk is intended for Rubyists of all experience levels who would like to gain a deeper understanding of memory management in Ruby MRI and learn about the new GC.compact method introduced in Ruby 2.7. I will start by telling a story of a bug that was reported in the MongoDB Ruby Driver gem and how that lead me to learn about the new manual memory compaction feature in Ruby MRI. I'll retrace my steps, from learning about the memory heap and mark and sweep garbage collection to finally understanding how memory compaction works, and thus figuring out what was causing the bug in my gem! I'll also talk about how memory compaction impacts Ruby developers who write and maintain C extensions.

By the end of this talk, attendees should be able to understand the following concepts at a high level:
- The structure and use of the memory heap
- Ruby MRI garbage collection
- Memory bloat and how that impacts Ruby MRI
- Memory compaction, its implementation in Ruby 2.7, and how it impacts C extensions

## Bio
Emily Giurleo is a software engineer at MongoDB, where she helps maintain the Ruby Driver and Mongoid Object-Document Mapper.

**Comment by dmitrinesterenko** [comment]
@egiurleo This sounds cool!!! Are you available to give this talk at the October 14th NYC.rb meetup?

**Comment by egiurleo** [comment]
@dmitrinesterenko I'm glad you think so! I'm not available the evening of October 14 -- would it be possible to plan for November instead?

**Comment by dmitrinesterenko** [comment]
@egiurleo we can plan for November, it should be the second Wednesday of the month, so 11/11 (reads like a lucky date to me). Can you make it then?

**Comment by egiurleo** [comment]
@dmitrinesterenko Yes that would be perfect! Would this be in the evening (eastern time)?

**Comment by notable-dmitri** [comment]
@egiurleo yes evening in EST, we usually start around 5:30 PM EST and schedule the talk to start at 6PM. Let me know if that time works or we can adjust it a bit so that it does.

**Comment by dmitrinesterenko** [comment]
> @dmitrinesterenko Yes that would be perfect! Would this be in the evening (eastern time)?

@egiurleo yes evening in EST, we usually start around 5:30 PM EST and schedule the talk to start at 6PM. Let me know if that time works or we can adjust it a bit so that it does.

**Comment by egiurleo** [comment]
That's perfect! How long should the talk be?

**Comment by dmitrinesterenko** [comment]
@egiurleo we usually try to have the talks not to go over 40 minutes, but aside that flexible upper boundary the length is up to you.

**Comment by egiurleo** [comment]
Okay, that's great. I'm going to start working on my talk the week before and will let you know how long I expect it to run.

**Comment by egiurleo** [comment]
@dmitrinesterenko When you have some time, could you add some info the [Nov. 11 meetup event](https://www.meetup.com/NYC-rb/events/rsjnsrybcpbpb/)? I'll share it with my networks and hopefully get some of my friends to come :)

**Comment by dmitrinesterenko** [comment]
@egiurleo we're updating the event description tomorrow, will let you know as soon as it is. Is this an OK description?

### “The Bug that Forced Me to Understand Memory Compaction” by Emily Giurleo 

Emily says: “In this talk, I’ll tell you a story about how one bug forced me to learn all about memory management in Ruby. By the end of this talk, you should understand how memory is allocated on the heap, how Ruby implements garbage collection, and what memory compaction is all about!”

...perhaps adding the full description would be good as well. I like the bullet points that describe the take aways for attendees.

**Comment by egiurleo** [comment]
That's great! And yeah I agree with adding the takeaways so people know what they'll (hopefully) learn :)

**Comment by dmitrinesterenko** [comment]
Hi @egiurleo I updated the [event description](https://www.meetup.com/NYC-rb/events/rsjnsrybcpbpb/), please share it out. We'll have a newsletter out this weekend that will mention it as well.

**Comment by egiurleo** [comment]
Awesome, thank you! I will start sharing :D
