### ISSUE TITLE
[Talk Proposal] Asynchronous Ruby

### ISSUE THREAD

**Issue by bruno-** [NYCrb/devpunks#87]
### Abstract

With version 3.0 asynchronous programming in Ruby became a reality! We have [the awesome `async` gem and its ecosystem](https://brunosutic.com/blog/async-ruby), but there are also native approaches allowing you to gain the benefits of asynchronous paradigm using just the built-in Ruby methods - no frameworks required.

From Rails to core Ruby, there's a lot of async innovation going on. This talk aims to give you the overview of this ecosystem in Ruby and answer these questions:

- What are the benefits of asynchronous Ruby?
- Does it work with Rails?
- Should you use `async` gem or just built-in Ruby methods?
- How do you use it? How to get started?

Async is where a lot of the advancement of the Ruby language is happening. Join me in this talk and find all about it!

### Bio

Bruno is a dad of two beautiful children, early adopter of Asynchronous Ruby, and a command line aficionado. He's been a Ruby developer for more than 10 years now, working for both consultancies and product companies. The most fun he's had was working for an IOT company where he had to figure out how to make connected locks play "beep-bop" sounds. He's currently working on his own product (shhh, it's a secret!).

**Comment by dmitrinesterenko** [comment]
@bruno- here is the video recording of your talk and presentation https://www.youtube.com/watch?v=T8YF8qBoBAA
